# PowerAPI CircleCI configuration file
version: 2.1
jobs:
  publish-release:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - run:
          name: check git tag with package version
          command: |
            python3 -c "import os, rapl_formula; exit(os.environ.get('CIRCLE_TAG', '?')[1:] != rapl_formula.__version__)"

      - run:
          name: prepare environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -U pip twine

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = powerapi" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: generate package
          command: |
            python3 setup.py sdist bdist_wheel

      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  build-n-publish:
    jobs:
      - publish-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
